services:
    _defaults:
        autowire: true
        autoconfigure: true

    Html\TwigComponentBundle\Twig\Block\:
        resource: '../../Twig/Block/'
    
    Html\TwigComponentBundle\Twig\Inline\:
        resource: '../../Twig/Inline/'
    
    Html\TwigComponentBundle\Twig\Void\:
        resource: '../../Twig/Void/'